name: dart_examples
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ahaggi <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  spreadsheet_decoder: ^1.0.0
  rxdart: ^0.21.0

  

dev_dependencies:
  test: ^1.0.0
  build_runner: '>=0.8.10 <0.11.0'
  build_web_compilers: '>=0.3.6 <0.5.0'

  